users:
    pattern:  /user/:name
    defaults: { _controller: UserBundle:User:detail }

    pattern:  /users
    defaults: { _controller: UserBundle:User:index }

    pattern:  /user/edit/:id
    defaults: { _controller: UserBundle:User:edit }

register:
    pattern: /register
    defaults: { _controller: UserBundle:User:register }
