user:
    pattern:  /user/:name
    defaults: { _controller: UserBundle:User:detail }
users:
    pattern:  /user
    defaults: { _controller: UserBundle:User:index }

register:
    pattern: /register
    defaults: { _controller: UserBundle:User:register }
