Application\UserBundle\User:
    properties:
        email:
            - NotNull: ~
        name:
            - NotNull: ~

Application\UserBundle\Registration:
    properties:
        email:
            - NotNull: ~
        name:
            - NotNull: ~