security.config:
  providers:
    default:
      password_encoder: sha1
      entity: { class: UserBundle:User, property: email }
  encoders:
    Application\UserBundle\Entity\User: sha1
  firewalls:
    public:
      pattern: /.*
      anonymous: true
      form_login:
        provider: default
        use_referer: true
      logout: true
    private:
      pattern: /user/edit.*
      form_login:
        provider: default
        use_referer: true
      logout: true
    content:
      pattern: /content/[create|modify|delete]+
      form_login:
        provider: default
        use_referer: true
      logout: true

  access_control:
    - { path: /my/?.*, role: ROLE_OWNER }
    - { path: /user/edit, role: ROLE_OWNER }
    - { path: /content/[create|modify|delete]+, role: ROLE_OWNER }
    - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }


security.acl:
  connection: default