app.config:
    charset:       UTF-8
    error_handler: null
    csrf_secret:   xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:
        enabled: true
        annotations: true
    templating:    {} #assets_version: SomeVersionScheme
    translator:    { fallback: en }
    session:
        default_locale: ru
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig.config:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

## Doctrine Configuration
doctrine.dbal:
    driver:   PDOMySql
    host:     localhost
    dbname:   shop
    user:     root
    password: null
    event_manager_class:  Doctrine\Common\EventManager
    configuration_class:  Doctrine\DBAL\Configuration
    wrapper_class:        ~
    options:              []

doctrine.orm: ~

## Swiftmailer Configuration
swiftmailer.config:
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com
    username:   a.diesel@gmail.com
    password:   ghbrjkmyj


security.config:
  providers:
    frontend:
      entity: { class: UserBundle:User, property: email }
    backend:
      password_encoder: sha1
      admin: { password: admin, roles: ['ROLE_USER', 'ROLE_ADMIN'] }
  firewalls:
    backend:
      pattern: /admin/.*
      form-login: true
    main:
      form-login: true
      logout:     true
      pattern:    /my/?.*
      my:
        check_path : /login
        login_path : /login
        failure_path : null
        always_use_default_target_path : false
        default_target_path : /
        target_path_parameter : _target_path
        use_referer : false

  access_control:
    - { path: /.*, role: ROLE_USER }
    - { path: /admin/.*, role: ROLE_ADMIN }


parameters:
  email.from: a.diesel@gmail.com
  