imports:
    - { resource: security.yml }

app.config:
    charset:       UTF-8
    error_handler: null
    csrf_secret:   xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    {} #assets_version: SomeVersionScheme
    translator:    { fallback: en }
    session:
        default_locale: ru
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig.config:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

## Doctrine Configuration
doctrine.dbal:
  driver:   pdo_mysql
  default_connection: default
  connections:
      default:
        dbname: shop
        user:             root
        password:         null
        host:             localhost

doctrine.orm:
  auto_generate_proxy_classes: %kernel.debug%
  mappings:
    UserBundle: ~
  auto_generate_proxy_classes: true
  proxy_namespace: Proxies
  proxy_dir: %kernel.cache_dir%/doctrine/orm/Proxies
  default_entity_manager: default
  default_connection: default
  metadata_cache_driver: array
  query_cache_driver: array
  result_cache_driver: array

## Swiftmailer Configuration
swiftmailer.config:
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com
    username:   a.diesel@gmail.com
    password:   ghbrjkmyj



parameters:
  email.from: a.diesel@gmail.com
