app.config:
    charset:       UTF-8
    error_handler: null
    csrf_secret:   xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    {} #assets_version: SomeVersionScheme
    translator:    { fallback: en }
    session:
        default_locale: ru
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig.config:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

## Doctrine Configuration
doctrine.dbal:
    driver:   PDOMySql
    event_manager_class:  Doctrine\Common\EventManager
    configuration_class:  Doctrine\DBAL\Configuration
    wrapper_class:        ~
    options:              []
    connections:
      default:
        host:     localhost
        dbname:   shop
        user:     root
        password: null
      production:
        host:     localhost
        dbname:   shop
        user:     root
        password: null

doctrine.orm:
    auto_generate_proxy_classes: %kernel.debug%
    mappings:
        UserBundle: ~

## Swiftmailer Configuration
swiftmailer.config:
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com
    username:   a.diesel@gmail.com
    password:   ghbrjkmyj


security.config:
  providers:
    default:
      password_encoder: sha1
      entity: { class: UserBundle:User, property: username }

  firewalls:
    public:
      pattern: /.*
      anonymous: true
      form_login: { provider: default }
      logout: true

  access_control:
    - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }



parameters:
  email.from: a.diesel@gmail.com
