homepage:
    pattern:  /
    defaults: { _controller: HomepageBundle:Home:index }

hello:
    resource: HelloBundle/Resources/config/routing.yml

user:
    resource: UserBundle/Resources/config/routing.yml
    prefix: /user

security:
    resource: SecurityBundle/Resources/config/routing.yml
