homepage:
    pattern:  /
    defaults: { _controller: HomeBundle:Home:index }

registration:
    pattern: /registration
    defaults: { _controller: UserBundle:Registration:Registration }

_captcha:
    pattern: /_captcha
    defaults: { _controller: CaptchaBundle:Captcha:captcha }

_security_login:
    pattern: /login
    defaults: { _controller: UserBundle:Security:login }

_security_check:
    pattern: /login_check
    
_security_logout:
    pattern: /logout

user:
  resource: @UserBundle/Resources/config/routing.yml
  prefix:   /user

content:
  resource: @ContentBundle/Resources/config/routing.yml
  prefix:   /content