homepage:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Default:index }

registration:
    pattern: /registration
    defaults: { _controller: UserBundle:User:Registration }

_security_login:
    pattern: /login
    defaults: { _controller: UserBundle:Security:login }

_security_check:
    pattern: /login_check
    
_security_logout:
    pattern: /logout