homepage:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Default:index }

hello:
    resource: HelloBundle/Resources/config/routing.yml
    
_security_login:
    pattern: /login
    defaults: { _controller: UserBundle:Security:login }

_security_check:
    pattern: /login_check
    
_security_logout:
    pattern: /logout