_main:
    resource: routing.yml

_profiler:
    resource: WebProfilerBundle/Resources/config/routing/profiler.xml
    prefix:   /_profiler

test:
  pattern: /test/register
  defaults: { _controller: TestBundle:Test:register }