article_index:
  pattern: /
  defaults: { _controller: ContentBundle:Article:Index }

article_create:
  pattern: /create
  defaults: { _controller: ContentBundle:Article:Create }

article_modify:
  pattern: /modify/{id}
  defaults: { _controller: ContentBundle:Article:Modify }

article_delete:
  pattern: /delete/{id}
  defaults: { _controller: ContentBundle:Article:Delete }

article_view:
  pattern: /{id}
  defaults: { _controller: ContentBundle:Article:View }