news_index:
  pattern: /
  defaults: { _controller: ContentBundle:News:Index }

news_create:
  pattern: /create
  defaults: { _controller: ContentBundle:News:Create }

news_modify:
  pattern: /modify/{id}
  defaults: { _controller: ContentBundle:News:Modify }

news_delete:
  pattern: /delete/{id}
  defaults: { _controller: ContentBundle:News:Delete }

news_view:
  pattern: /{id}
  defaults: { _controller: ContentBundle:News:View }