content_view:
  pattern: /{id}
  defaults: { _controller: ContentBundle:Content:View }

content_index:
  pattern: /
  defaults: { _controller: ContentBundle:Content:Index }

content_create:
  pattern: /create
  defaults: { _controller: ContentBundle:Content:Create }

content_modify:
  pattern: /modify/{id}
  defaults: { _controller: ContentBundle:Content:Modify }

content_delete:
  pattern: /delete/{id}
  defaults: { _controller: ContentBundle:Content:Delete }